
baseURL = "https://mattjon.es/countersteering/"
languageCode = "en-gb"
[params]
    title = "Countersteering"
    description = "A journal by <a href=\"https://mattjon.es\">Matt Jones</a>, mainly about transport, design and technology."
sectionPagesMenu = "main"
RelativeURLs=true
CanonifyURLs=true
[menu]
    [[menu.main]]
    identifier = "home"
    name       = "Home Page"
    url        = "/"
    weight     = 0
