#+hugo_base_dir: ../../
#+hugo_section: linknotes

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t
#+MACRO: abbr *[$1]: $2
#+author: Matt Jones

* Link Notes                                              :@linknotes:

** TODO Notes 18.7.2023

**** Tourists flock to Death Valley hoping to experience heat record

https://www.bbc.co.uk/news/av/world-us-canada-66229286



** Notes 14.7.2023                                  :Environment:Transport:Politics:
:PROPERTIES:
:EXPORT_DATE: 2023-07-14
:EXPORT_HUGO_BUNDLE: 20230714
:EXPORT_HUGO_RESOURCES: :src "ai-image-planner.jpg" :title "VanMoof bicycle leaning against a garage door" :name "planner"
:EXPORT_HUGO_RESOURCES+: :src "stone-henge.jpg" :title "35mm film photo of Stone Henge" :name "stonehenge"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="stonehenge"
    command="Resize"
    options="1200x webp"
    imageCaption="35mm film photo of Stone Henge" 
    imageURL="https://commons.wikimedia.org/wiki/File:StonehengeInfraRedE4ProcessKodakFilm-001.tif"
    imageAttrib=""
    imageLicense="Public Domain"
    licenseURL="https://en.wikipedia.org/wiki/Public_domain">}}
#+end_export
*** Today's notes

+ [[/blog/links/2023/07/14#stonehenge-tunnel-is-approved-by-government][Stonehenge tunnel is approved by government]]: Moar roads!
+ [[/blog/links/2023/07/14#wealth-taxes-will-cause-the-rich-to-flee-12-wealth-tax-myths-debunked][Wealth taxes will cause the rich to flee’: 12 wealth tax myths debunked]] The injustice of not taxing the rich

#+begin_export hugo
<!--more-->
#+end_export
---
**** Stonehenge tunnel is approved by government

https://www.bbc.co.uk/news/uk-england-wiltshire-66201424

#+begin_export hugo
{{< imgproc name="planner"
    command="Resize"
    options="1200x webp"
    imageCaption="AI generated photo of an officious looking male proudly overseeing the building of a road through the countryside" 
    imageURL="https://openai.com/dall-e-2"
    imageAttrib="DALL-e 2"
    imageLicense="Public Domain"
    licenseURL="https://en.wikipedia.org/wiki/Public_domain">}}
#+end_export

Why is the future for anything good in the world at the mercy of men - still thinking it's the 1960s - getting all excited at the prospect of taking their internal combustion engines, or possibly half-tonne lithium-ion batteries - over tarmac freshly laid over or under the countryside and, in this case, near to an ancient and globally important monument. 

This is execrable in every sense, as well as deeply irresponsible for obvious reasons. Meanwhile neighbouring Wales has simply stopped building new roads.   

---

**** Wealth taxes will cause the rich to flee’: 12 wealth tax myths debunked 

https://www.taxjustice.uk/blog/wealth-taxes-will-cause-the-rich-to-flee-11-wealth-tax-myths-debunked

For as long as I can remember - with the exception of the pandemic when there was suddenly money to pay for stuff - the government narrative around paying for public services has consistently been around the false dichotomy between austerity and raising taxes on low and middle-income earners. 

The idea of taxing the richest in society is quickly batted away by politicians regardless of which party is in power, possibly because it's the richest in society that donate large sums of money to both parties. But this couldn't be more unjust, because just a 1% tax on millionaire households over five years would raise £260 billion. That's £80 billion more than the entire NHS yearly budget. 

    

** Notes 13.7.2023                                  :Cycling:Politics:Gaming:
:PROPERTIES:
:EXPORT_DATE: 2023-07-13
:EXPORT_HUGO_BUNDLE: 20230713
:EXPORT_HUGO_RESOURCES: :src "vanmoof.jpg" :title "VanMoof bicycle leaning against a garage door" :name "vanmoof"
:EXPORT_HUGO_RESOURCES+: :src "hollywood-strike.jpg" :title "Hollywood" :name "hollywood"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="vanmoof"
    command="Resize"
    options="1200x webp"
    imageCaption="Photo of a white VanMoof bicycle leaning against a blue garage door" 
    imageURL="https://flickr.com/photos/kwanzshop/13849830555/"
    imageAttrib="Kwanz"
    imageLicense="CC BY 2.0"
    licenseURL="https://creativecommons.org/licenses/by/2.0/">}}
#+end_export
*** Today's notes

+ [[/blog/links/2023/07/13#bicycle-manufacture-vanmoof-is-in-trouble][VanMoof is in trouble:]] Dutch bicycle company is in financial trouble for lots of complex reasons
+ [[/blog/links/2023/07/13#akka-arrh][Akka Arrh: ]]The relaunch of a 'lost' Atari arcade game
+ [[/blog/links/2023/07/13#hollywood-actors-announce-strike-in-first-joint-action-with-writers-in-60-years][Hollywood actors announce strike in first joint action with writers in 60 years:]] Hollywood stars strike for better pay and concern about AI

#+begin_export hugo
<!--more-->
#+end_export
---
**** Bicycle manufacturer VanMoof is in trouble

https://www.dutchnews.nl/2023/07/dutch-bicycle-maker-vanmoof-granted-protection-from-creditors/

Electric-assist Pedal Cycles (EAPCs) bring with them a whole load of complexity in supply chain, manufacture and ongoing maintenance over and above the simple mechanics of a regular bicycle. 

Margins in the bike industry are tight at the best of times, however I think VanMoofs problems are partly of their own making due to the tech-heavy, proprietory nature of their products (their bikes' locking mechanism seems to use some kind of app-based encryption system) as well as their reliance on private external finance rather than being profitable. 

That said, at a time when climate action is pressing and we need people to ditch their cars, we need governments to step in and provide subsidies to help absorb these increasing supply costs, as well as lower the purchase costs  so that the bike industry in general can stay afloat. 

---
**** Akka Arrh

https://atari.com/products/akka-arrh

I'm all over this game. From the legendary Llamasoft, this is a re-imagining of a 'lost' Atari arcade game, the story of which is explained by Jeff Minter himself in [[https://www.youtube.com/watch?v=qtkifcXjJ9Q][a video uploaded to Youtube]].

Minter was approached by Atari to redevelop a game from their catalogue of arcade classics, and Akka Arrh was what he chose, the challenge being to breathe life into game that never launched.

It's available for pretty much every gaming platform thanks to Minter's partner Ivan Zorzin, who was responsible for the complex porting work.  


---
**** Hollywood actors announce strike in first joint action with writers in 60 years

https://www.theguardian.com/us-news/2023/jul/13/hollywood-actors-union-recommends-strike-as-talks-deadline-passes

#+begin_export hugo
{{< imgproc name="hollywood"
    command="Resize"
    options="1200x webp"
    imageCaption="Warner Bros. Studio during the Conference of Studio Unions strike, Los Angeles, 1945" 
    imageURL="https://digital.library.ucla.edu/catalog/ark:/21198/zz002hj471"
    imageAttrib="UCLA Charles E. Young Research Library Department of Special Collections"
    imageLicense="CC BY 4.0"
    licenseURL="https://creativecommons.org/licenses/by/4.0/">}}
#+end_export


Public Sector worker strikes for better pay and conditions are now a common occurance here in the UK because of our dreadful government who treat people who work in public service abysmally.

Now Hollywood actors are on strike for the first joint action with writers in over 60 years. Because the dynamics of exchanging labour for wage payment are the same regardless of the sectors you work in. 


** Link Notes 10 March 2023                        :Politics:Herne:BBC:
:PROPERTIES:
:EXPORT_DATE: 2023-03-10
:EXPORT_HUGO_BUNDLE: 20230310
:EXPORT_HUGO_RESOURCES: :src "herne.jpg" :title "Herne the Hunter" :name "herne"
:EXPORT_FILE_NAME: index
:END:
#+begin_export hugo
{{< imgproc name="herne"
    command="Resize"
    options="1200x webp"
    imageCaption="1840s illustration of Herne the Hunter riding a horse" 
    imageURL="https://commons.wikimedia.org/wiki/File:Herne_the_Hunter.jpg"
    imageAttrib="Wikimedia Commons"
    imageLicense="Public Domain"
    licenseURL="">}}
#+end_export
*** Today's links

What I'm thinking about today. Interested in the power of music and memory, or how the former can trigger the latter. Also, crisis at the BBC.  

+ [[/blog/links/2023/03/10#herne-the-hunter][Herne the Hunter]]: Pagan myths, social justice and 80s TV
+ [[/blog/links/2023/03/10#gary-lineker-andrew-neil-and-the-bbc-s-real-impartiality-crisis][Gary Lineker, Andrew Neil and the BBC’s Real Impartiality Crisis]]: The right-wing free-speech hyprocrites
+ [[/blog/links/2023/03/10#on-this-day-from-the-archive][On this day, from the archive]]: Nautilus Goes Spatial
#+begin_export hugo
<!--more-->
#+end_export

**** Herne the Hunter

https://en.wikipedia.org/wiki/Herne_the_Hunter

I've been thinking about my happy childhood; the long summers, the freedom, the predictable weather, the constructive boredom associated with the contraints of only four television channels. There's one particular programme (and its soundtrack) that reminds me of this period more than anything. 'Robin of Sherwood' was an influential ITV adaption of Robin Hood, introducing pagan mythology into its story of struggle against oppression. 

The mythical figure Herne is presented as a sort of commissioner for Robin Hood to protect the poor against the oppressive regime of the Sherriff of Nottingham. His appearance in the series was accompanied by  ambient and arpeggiated synth sounds by the band Clannad, who provided the sound track to the series. It's this track in particular that transports me to a specific time and place: a bedroom on a hot summer evening (in around 1985), standing in front of a tape deck and reading the album sleeve notes from the soundtrack.

Thinking about writing a longer post about this particular depiction of Herne.  

---

**** Gary Lineker, Andrew Neil and the BBC’s Real Impartiality Crisis

https://bylinetimes.com/2023/03/09/gary-lineker-andrew-neil-and-the-bbcs-real-impartiality-crisis/

Adam Bienkov lays bare the rank hypocrisy shown by the right wing in relation to BBC impartiality. 

---

**** On this day, from the archive

+ [19 years ago: Nautilus Goes Spatial](https://mattjon.es/blog/2004/03/nautilus-goes-spatial/): I've been a Linux user for about 25 years. Here are some thought about changes' to Gnome's file manager, created by Andy Hertzfeld (who helped to create the user interface on the original Apple Macintosh). 



** Link Notes 8 March 2023                         :Politics:Asylum:Blogging:
:PROPERTIES:
:EXPORT_DATE: 2023-03-08
:EXPORT_HUGO_BUNDLE: 20230308
:EXPORT_FILE_NAME: index
:END:
*** Today's links
+ [[/blog/links/2023/03/08#rishi-sunak-extinguishing-the-right-to-seek-refugee-protection-in-uk][Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’]]: Stop the Tories
+ [[/blog/links/2023/03/08#ox-hugo-org-to-markdown-for-hugo][Ox-Hugo]]: My somewhat esoteric blogging system of choice
+ [[/blog/links/2023/03/08#on-this-day-from-the-archive][On this day, from the archive]]: The Internet Book List
#+begin_export hugo
<!--more-->
#+end_export

**** Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’

https://www.theguardian.com/uk-news/2023/mar/07/suella-braverman-asylum-migration-bill-law-change-small-boats

The United Kingdom has a long history of welcoming and protecting those seeking refuge from conflict and persecution around the world. It's why the UK is a diverse place.

Sunak and Braverman are pandering to the extreme-right with this disgusting plan to criminalise desperate people seeking a better life. 

Shame on all involved.  

---

**** Ox-Hugo: Org to Markdown for Hugo

https://ox-hugo.scripter.co

For quite a number of years now, this site has been produced using a static-site generator called Hugo. I write Markdown files, run 'hugo' and and within a fraction of a second 1800+ posts are packaged up into a set of HTML files ready to deploy. If that wasn't esoteric enough, I use Emacs with Org Mode to write and manage my posts in one .org file. OrgMode is basically a todo / planner system for Emacs with lots of nerdy features that I'll never use or fully understand.   






---

**** On this day, from the archive

+ [20 years ago: The Internet Book List](https://mattjon.es/blog/2003/03/the-internet-book-list/): A note on the launch of the Internet Book List: a sort of IMDB for books. 



* Code
(defun hugo-slugify (start end)
  (interactive "r")
  (if (use-region-p)
      (let ((regionp (buffer-substring start end)))
        (save-excursion
          (delete-region start end)
          (insert
           (replace-regexp-in-string
            "[^a-z0-9-]" ""
            (replace-regexp-in-string
             "\s+" "-"
             (downcase regionp)
             )))))))

* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# org-hugo-footer: "\n\n[//]: # \"Exported with love from a post written in Org mode\"\n[//]: # \"- https://github.com/kaushalmodi/ox-hugo\""
# End:


