#+hugo_base_dir: ../../
#+hugo_section: linknotes

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t

#+author: Matt Jones

* Link Notes                                              :@linknotes:
** Link Notes 8 March 2023                                         :politics:asylum:blogging:
:PROPERTIES:
:EXPORT_DATE: 2023-03-08
:EXPORT_HUGO_BUNDLE: 20230308
:EXPORT_FILE_NAME: index
:END:
*** Today's links
+ [[/blog/links/2023/03/08#rishi-sunak-extinguishing-the-right-to-seek-refugee-protection-in-uk][Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’]]: Stop the Tories
+ [[/blog/links/2023/03/08#ox-hugo-org-to-markdown-for-hugo][Ox-Hugo]]: My somewhat esoteric blogging system of choice
+ [[/blog/links/2023/03/08#on-this-day-from-the-archive][On this day, from the archive]]: The Internet Book List


#+begin_export hugo
<!--more-->
#+end_export

**** Rishi Sunak ‘extinguishing the right to seek refugee protection in UK’

https://www.theguardian.com/uk-news/2023/mar/07/suella-braverman-asylum-migration-bill-law-change-small-boats

The United Kingdom has a long history of welcoming and protecting those seeking refuge from conflict and persecution around the world. It's why the UK is a diverse place.

Sunak and Braverman are pandering to the extreme-right with this disgusting plan to criminalise desperate people seeking a better life. 

Shame on all involved.  

---

**** Ox-Hugo: Org to Markdown for Hugo

https://ox-hugo.scripter.co

For quite a number of years now, this site has been produced using a static-site generator called Hugo. I write Markdown files, run 'hugo' and and within a fraction of a second 1800+ posts are packaged up into a set of HTML files ready to deploy. If that wasn't esoteric enough, I use Emacs with Org Mode to write and manage my posts in one .org file. OrgMode is basically a todo / planner system for Emacs with lots of nerdy features that I'll never use or fully understand.   






---

**** On this day, from the archive

+ [20 years ago: The Internet Book List](https://mattjon.es/blog/2003/03/the-internet-book-list/): A note on the launch of the Internet Book List: a sort of IMDB for books. 





* Code
(defun hugo-slugify (start end)
  (interactive "r")
  (if (use-region-p)
      (let ((regionp (buffer-substring start end)))
        (save-excursion
          (delete-region start end)
          (insert
           (replace-regexp-in-string
            "[^a-z0-9-]" ""
            (replace-regexp-in-string
             "\s+" "-"
             (downcase regionp)
             )))))))

#+begin_export hugo
{{< imgproc name="sentinel2"
    command="Resize"
    options="1200x"
    imageCaption="Needlepoint tapestry representation of The Sentinel—video game created by Geoff Crammond—in its version on ZX Spectrum 55 × 46 cm – 2022" 
    imageURL="https://www.marine.st/en"
    imageAttrib="Marine Beaufils"
    imageLicense=""
    licenseURL="">}}
#+end_export

* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# org-hugo-footer: "\n\n[//]: # \"Exported with love from a post written in Org mode\"\n[//]: # \"- https://github.com/kaushalmodi/ox-hugo\""
# End:
